version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  app:
    build: .
    command: bin/rails s -p 3001 -b "0.0.0.0"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/src/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db
volumes:
  bundle:
  mysql_data:
