default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: db

development:
  <<: *default
  database: snipe

test:
  <<: *default
  database: snipe_test

production:
  <<: *default
  database: snipe
