default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: db

development:
  <<: *default
  database: snipe_development

test:
  <<: *default
  database: snipe_test
<% if ENV['CI'] == 'yes' %>
  host: localhost
  port: 3306
<% end %>

production:
  <<: *default
  database: snipe
